version: '3.9'

services:
  postgres:
    container_name: postgres
    image: docker.io/postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    network:
      - com

  app:
    build: .
    container_name: app
    image: app
    environment:
      DATABASE_URI: 'postgres://user:pass@postgres:5432/postgres?sslmode=disable'
      ADDRESS: ':8080'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    network:
      - com

volumes:
  pg-data:

networks:
  com: {}
