app:
  name: 'gophermart'
  version: '0.0.1'
  workers_count: 5
  accreal_system_address: http://127.0.0.1:8082

http:
  address: ':8080'

logger:
  log_level: 'debug'
  rollbar_env: 'gophermart'

postgres:
  pool_max: 2
  migration_dir: 'migrations'
